# Generated by Django 2.2.13 on 2020-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0002_auto_20190406_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.TextField(),
        ),
    ]
